module.exports = {
  content: ["./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      textColor: {
        theme: {
          primary: "var(--color-primary)",
          "primary-focus": "var(--color-primary-focus)",
          "primary-content": "var(--color-primary-content)",
          "primary-muted": "var(--color-primary-muted)",
          secondary: "var(--color-secondary)",
          "secondary-focus": "var(--color-secondary-focus)",
          "secondary-content": "var(--color-secondary-content)",
          accent: "var(--color-accent)",
          "accent-focus": "var(--color-accent-focus)",
          "accent-content": "var(--color-accent-content)",
          neutral: "var(--color-neutral)",
          "neutral-focus": "var(--color-neutral-focus)",
          "neutral-content": "var(--color-neutral-content)",
          "base-100": "var(--color-base-100)",
          "base-200": "var(--color-base-200)",
          "base-300": "var(--color-base-300)",
          "base-400": "var(--color-base-400)",
          "base-content": "var(--color-base-content)",
          "base-content-muted": "var(--color-base-content-muted)",
          info: "var(--color-info)",
          success: "var(--color-success)",
          warning: "var(--color-warning)",
          error: "var(--color-error)",
        },
      },
      backgroundColor: {
        theme: {
          primary: "var(--color-primary)",
          "primary-focus": "var(--color-primary-focus)",
          "primary-content": "var(--color-primary-content)",
          "primary-muted": "var(--color-primary-muted)",
          secondary: "var(--color-secondary)",
          "secondary-focus": "var(--color-secondary-focus)",
          "secondary-content": "var(--color-secondary-content)",
          accent: "var(--color-accent)",
          "accent-focus": "var(--color-accent-focus)",
          "accent-content": "var(--color-accent-content)",
          neutral: "var(--color-neutral)",
          "neutral-focus": "var(--color-neutral-focus)",
          "neutral-content": "var(--color-neutral-content)",
          "base-100": "var(--color-base-100)",
          "base-200": "var(--color-base-200)",
          "base-300": "var(--color-base-300)",
          "base-400": "var(--color-base-400)",
          "base-content": "var(--color-base-content)",
          "base-content-muted": "var(--color-base-content-muted)",
          info: "var(--color-info)",
          success: "var(--color-success)",
          warning: "var(--color-warning)",
          error: "var(--color-error)",
        },
      },
      borderColor: {
        theme: {
          primary: "var(--color-primary)",
          "primary-focus": "var(--color-primary-focus)",
          "primary-content": "var(--color-primary-content)",
          "primary-muted": "var(--color-primary-muted)",
          secondary: "var(--color-secondary)",
          "secondary-focus": "var(--color-secondary-focus)",
          "secondary-content": "var(--color-secondary-content)",
          accent: "var(--color-accent)",
          "accent-focus": "var(--color-accent-focus)",
          "accent-content": "var(--color-accent-content)",
          neutral: "var(--color-neutral)",
          "neutral-focus": "var(--color-neutral-focus)",
          "neutral-content": "var(--color-neutral-content)",
          "base-100": "var(--color-base-100)",
          "base-200": "var(--color-base-200)",
          "base-300": "var(--color-base-300)",
          "base-400": "var(--color-base-400)",
          "base-content": "var(--color-base-content)",
          "base-content-muted": "var(--color-base-content-muted)",
          info: "var(--color-info)",
          success: "var(--color-success)",
          warning: "var(--color-warning)",
          error: "var(--color-error)",
        },
      },
    },
  },
  plugins: [],
};
