name: The pipeline

on:
  push:
    branches: [master, develop]
    tags: '*'

  pull_request:
    types: [opened, synchronize]

jobs:

  avoid_redundancy:
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  lint:
    runs-on: ubuntu-18.04

    steps:
      - name: CheckOut
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: NPM private login
        run: echo ${{ secrets.NPM_AUTH_TOKEN }} >> ./.npmrc

      - name: Install dependencies
        run: npm ci --no-optional

      - name: Build
        run: npm run build --if-present

      - name: Depcheck
        run: npm run lint

  docker:
    needs: [lint]
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Registry Turinlabs
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - id: docker-tag
        name: "Getting tag from github.ref"
        uses: yuya-takeyama/docker-tag-from-github-ref-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          secrets: |
            npm_auth_token=${{ secrets.NPM_AUTH_TOKEN }}
          context: .
          platforms: linux/amd64
          push: true
          # push: ${{ startsWith(github.ref, 'refs/tags/')}}
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ steps.docker-tag.outputs.tag }}

      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        if: startsWith(github.ref, 'refs/tags/')
        with:
          args: |
            📦 New Release: ${{ github.repository }}:${{ steps.docker-tag.outputs.tag }}
